[package]
name = "memory"
version = "0.1.0"
description = "Memory paging logic"

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
readme = "../../README.md"
repository.workspace = true
rust-version.workspace = true
