name: Build xv6 Kernel Image & Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust nightly + binutils
        run: |
          rustup install nightly
          rustup component add llvm-tools-preview --toolchain nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binutils

      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-system-i386 nasm

      - name: Build xv6 image (release)
        run: cargo +nightly xtask image --profile release

      - name: Prepare artifact directory
        run: mkdir -p artifact

      - name: Copy xv6.img to artifact directory
        run: cp target/i686-xv6-none/release/xv6.img artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_xv6_kernel_image
          path: artifact/*

      - name: Run QEMU to test xv6.img boot
        run: |
          qemu-system-i386 -drive file=target/release/i686-xv6-none/xv6.img,format=raw -serial stdio -nographic -m 512M -boot c -display none &
          QEMU_PID=$!
          sleep 10
          kill $QEMU_PID
